services:
  cybersec_survey:
    image: cybersec_survey
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    restart: always
    ports:
      - "5306:5306"
    volumes:
      - survey_data:/app/data

volumes:
  survey_data:
